<?xml version="1.0" encoding="UTF-8"?>
<wsdl:definitions xmlns:ricevutans="http://annullaprescrittoricevuta.xsd.dem.sanita.finanze.it" xmlns:richiestans="http://annullaprescrittorichiesta.xsd.dem.sanita.finanze.it" xmlns:soap="http://schemas.xmlsoap.org/wsdl/soap/" xmlns:tns="http://annullaprescritto.wsdl.dem.sanita.finanze.it" xmlns:wsdl="http://schemas.xmlsoap.org/wsdl/" xmlns:xsd="http://www.w3.org/2001/XMLSchema" targetNamespace="http://annullaprescritto.wsdl.dem.sanita.finanze.it">
	<wsdl:types>
		<xsd:schema elementFormDefault="qualified">
			<xsd:import namespace="http://annullaprescrittorichiesta.xsd.dem.sanita.finanze.it" schemaLocation="AnnullaPrescrittoRichiesta.xsd"/>
		</xsd:schema>
		<xsd:schema elementFormDefault="qualified">
			<xsd:import namespace="http://annullaprescrittoricevuta.xsd.dem.sanita.finanze.it" schemaLocation="AnnullaPrescrittoRicevuta.xsd"/>
		</xsd:schema>
	</wsdl:types>
	<wsdl:message name="ricevuta">
		<wsdl:part name="AnnullaPrescrittoRicevuta" element="ricevutans:AnnullaPrescrittoRicevuta"/>
	</wsdl:message>
	<wsdl:message name="richiesta">
		<wsdl:part name="AnnullaPrescrittoRichiesta" element="richiestans:AnnullaPrescrittoRichiesta"/>
	</wsdl:message>
	<wsdl:portType name="annullaPrescrittoPT">
		<wsdl:operation name="annullaPrescritto">
			<wsdl:input message="tns:richiesta"/>
			<wsdl:output message="tns:ricevuta"/>
		</wsdl:operation>
	</wsdl:portType>
	<wsdl:binding name="annullaPrescrittoBinding" type="tns:annullaPrescrittoPT">
		<soap:binding style="document" transport="http://schemas.xmlsoap.org/soap/http"/>
		<wsdl:operation name="annullaPrescritto">
			<soap:operation soapAction="http://annullaprescritto.wsdl.dem.sanita.finanze.it/AnnullaPrescritto"/>
			<wsdl:input>
				<soap:body use="literal"/>
			</wsdl:input>
			<wsdl:output>
				<soap:body use="literal"/>
			</wsdl:output>
		</wsdl:operation>
	</wsdl:binding>
	<wsdl:service name="demAnnullaPrescritto">
		<wsdl:port name="demAnnullaPrescritto" binding="tns:annullaPrescrittoBinding">
			<soap:address location="http://localhost:9080/DemRicettaPrescrittoServicesWeb/services/demAnnullaPrescritto"/>
		</wsdl:port>
	</wsdl:service>
	<wsdl:documentation>Versione 1.2</wsdl:documentation>
</wsdl:definitions>
